/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.panels;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Salah
 */
public class Backup_panel extends javax.swing.JPanel {

    /**
     * Creates new form Backup_panel
     */
    String path = null;
    String fileName;

    public Backup_panel() throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        initComponents();
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    }

    public void restoreDB(String path) {

        String executeCmd = "C:/xampp/mysql/bin/mysql -u root  xcafe_db <" + path;
        System.out.println(executeCmd);
        Process runtimeProcess;

        try {
            runtimeProcess = Runtime.getRuntime().exec(new String[]{"cmd.exe", "/c", executeCmd});
            runtimeProcess.waitFor();

            JOptionPane.showMessageDialog(null, "Restore created successfully");

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    public void backupDataWithOutDatabase(String dumpExePath, String host, String port, String user, String database, String backupPath) {

        try {
            String batchCommand = dumpExePath + " -h " + host
                    + " --port " + port + " -u " + user + " " + database + " -r \"" + backupPath + "" + "\"";
            Process p = Runtime.getRuntime().exec(batchCommand);
            int processComplete = p.waitFor();

            if (processComplete == 0) {
                JOptionPane.showMessageDialog(null, "Backup created successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Could not create the backup");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getCause());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        backup_path_txt = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        pathchooser_backup_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        restore_filepath_txt = new javax.swing.JTextField();
        restore_btn = new javax.swing.JButton();
        pathchooser_restore_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Choose file location to save");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Backup");

        backup_path_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        save_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Save_30px.png"))); // NOI18N
        save_btn.setText("Save");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        pathchooser_backup_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_35px.png"))); // NOI18N
        pathchooser_backup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathchooser_backup_btnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Restore");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Choose file location to restore");

        restore_filepath_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        restore_btn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        restore_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Data Backup_30px.png"))); // NOI18N
        restore_btn.setText("Restore");
        restore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restore_btnActionPerformed(evt);
            }
        });

        pathchooser_restore_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Search_35px.png"))); // NOI18N
        pathchooser_restore_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathchooser_restore_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backup_path_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pathchooser_backup_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(restore_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(restore_filepath_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pathchooser_restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(82, 82, 82)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pathchooser_restore_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restore_filepath_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addComponent(restore_btn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pathchooser_backup_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(backup_path_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                        .addGap(97, 97, 97)
                        .addComponent(save_btn))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed

        Process p;

        try {
            Runtime runtime = Runtime.getRuntime();
            p = runtime.exec("C:/Program Files (x86)/MySQL/MySQL Server 5.0/bin/mysqldump.exe -uroot -proot --add-drop-database -B shop -r" + path); 
            int complete=p.waitFor();
            if (complete==0)System.out.println("done backup");
            else System.out.println("error backup"); 
            
        } catch (IOException | InterruptedException e) {
            System.out.println("ssss : "+e.getMessage());
        }
//        backupDataWithOutDatabase("C:\\Program Files (x86)\\MySQL\\MySQL Server 5.0\\bin\\mysqldump.exe", "localhost", "3306", "root", "xcafe_db", backup_path_txt.getText());
    }//GEN-LAST:event_save_btnActionPerformed

    private void pathchooser_backup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathchooser_backup_btnActionPerformed

        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        try {
            File f = fc.getSelectedFile();
            path = f.getAbsolutePath();
            path = path.replace("\\", "/");
            path = path + "_" + date + ".sql";
            backup_path_txt.setText(path);

        } catch (Exception e) {
        }

//        JFileChooser chooser = new JFileChooser();
//        int retval = chooser.showSaveDialog(null);
//        if (retval == JFileChooser.APPROVE_OPTION) {
//            File file = chooser.getSelectedFile();
//            if (file == null) {
//                return;
//            }
//            if (!file.getName().toLowerCase().endsWith(".sql")) {
//                file = new File(file.getParentFile(), file.getName() + ".sql");
//            }
//            String filepath = file.getAbsolutePath();
//            backup_path_txt.setText(filepath);
//        }
    }//GEN-LAST:event_pathchooser_backup_btnActionPerformed

    private void pathchooser_restore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathchooser_restore_btnActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("*.sql", "sql"));

        int retval = chooser.showOpenDialog(null);
        if (retval == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            if (file == null) {
                return;
            }

            String filepath = file.getAbsolutePath();
            restore_filepath_txt.setText(filepath);
        }
    }//GEN-LAST:event_pathchooser_restore_btnActionPerformed

    private void restore_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restore_btnActionPerformed
        restoreDB(restore_filepath_txt.getText());
    }//GEN-LAST:event_restore_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField backup_path_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton pathchooser_backup_btn;
    private javax.swing.JButton pathchooser_restore_btn;
    private javax.swing.JButton restore_btn;
    private javax.swing.JTextField restore_filepath_txt;
    private javax.swing.JButton save_btn;
    // End of variables declaration//GEN-END:variables
}
